[req]
distinguished_name = req_distinguished_name
[req_distinguished_name]
[v3_server]
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid,issuer
basicConstraints = CA:FALSE
keyUsage = critical, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth
subjectAltName = DNS:*.googleapis.com, DNS:googleapis.com
